# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Arduino-FOC
description: An Arduino Based Field Oriented Control(FOC) library documentation

baseurl: "/"  
url: "https://docs.simplefoc.com" 

remote_theme: simplefoc/simplefoc-docs-theme

# Set a path/url to a logo that will be displayed instead of the title
logo: "assets/images/logo.png"
favicon_ico: "assets/images/favicon.ico"

# Google Analytics Tracking (optional)
ga_tracking: "G-4G841WG9SD"

plugins:
  - jekyll-seo-tag
  - jekyll-toc
  - jekyll-remote-theme


# Footer content appears at the bottom of every page's main content
footer_content: "Copyright &copy; 2026. Distributed by an <a href=\"https://github.com/simplefoc/simplefoc.github.io/tree/master/LICENSE\">MIT license.</a>"

# External navigation links
nav_external_links:
  - title: "Docs archive"
    url: http://olddocs.simplefoc.com
    hide_icon: false # set to true to hide the external link icon - defaults to false
    fa_icon: "fa-archive" # Font Awesome icon class - defaults to "fa-external-link-alt"
    opens_in_new_tab: false # set to true to open this link in a new tab - defaults to false
  - title: "Docs in Chinese"
    url: https://docs.simplefoc.com/docs_chinese
    hide_icon: false # set to true to hide the external link icon - defaults to false
    fa_icon: "fa-language" # Font Awesome icon class - defaults to "fa-external-link-alt"
    opens_in_new_tab: false # set to true to open this link in a new tab - defaults to false